<?php

return [
    'edit' => 'fa-duotone fa-pen-to-square',
    'delete' => 'fa-duotone fa-trash',
    'save' => 'fa-duotone fa-floppy-disk',
    'school' => 'fa-duotone fa-school',
    'book' => 'fa-duotone fa-book',
    'money' => 'fa-duotone fa-money-bill',
    'user' => 'fa-duotone fa-user',
    'settings' => 'fa-duotone fa-gear',
    'home' => 'fa-duotone fa-house',
    'search' => 'fa-duotone fa-magnifying-glass',
    'filter' => 'fa-duotone fa-filter',
    'plus' => 'fa-duotone fa-plus',
    'minus' => 'fa-duotone fa-minus',
    'check' => 'fa-duotone fa-check',
    'times' => 'fa-duotone fa-xmark',
    'info' => 'fa-duotone fa-info',
    'exclamation' => 'fa-duotone fa-exclamation',
    'calendar' => 'fa-duotone fa-calendar',
    'clock' => 'fa-duotone fa-clock',
    'envelope' => 'fa-duotone fa-envelope',
    'phone' => 'fa-duotone fa-phone',
    'map' => 'fa-duotone fa-map',
    'lock' => 'fa-duotone fa-lock',
    'unlock' => 'fa-duotone fa-unlock',
    'eye' => 'fa-duotone fa-eye',
    'eye-slash' => 'fa-duotone fa-eye-slash',
    'upload' => 'fa-duotone fa-upload',
    'download' => 'fa-duotone fa-download',
    'file' => 'fa-duotone fa-file',
    'folder' => 'fa-duotone fa-folder',
    'image' => 'fa-duotone fa-image',
    'camera' => 'fa-duotone fa-camera',
    'video' => 'fa-duotone fa-video',
    'chart-bar' => 'fa-duotone fa-chart-bar',
    'chart-pie' => 'fa-duotone fa-chart-pie',
    'table' => 'fa-duotone fa-table',
    'list' => 'fa-duotone fa-list',
    'grid' => 'fa-duotone fa-table-cells',
    'bars' => 'fa-duotone fa-bars',
    'ellipsis' => 'fa-duotone fa-ellipsis',
    'arrow-left' => 'fa-duotone fa-arrow-left',
    'arrow-right' => 'fa-duotone fa-arrow-right',
    'chevron-down' => 'fa-duotone fa-chevron-down',
    'chevron-up' => 'fa-duotone fa-chevron-up',
    'star' => 'fa-duotone fa-star',
    'heart' => 'fa-duotone fa-heart',
    'bell' => 'fa-duotone fa-bell',
    'comment' => 'fa-duotone fa-comment',
    'graduation-cap' => 'fa-duotone fa-graduation-cap',
    'chalkboard-user' => 'fa-duotone fa-chalkboard-user',
    'sun' => 'fa-duotone fa-sun',
    'moon' => 'fa-duotone fa-moon',
    'calendar-days' => 'fa-duotone fa-calendar-days',
    'cart-shopping' => 'fa-duotone fa-cart-shopping',
    'book-open-reader' => 'fa-duotone fa-book-open-reader',
    'laptop-code' => 'fa-duotone fa-laptop-code',
    'pencil-paintbrush' => 'fa-duotone fa-pencil-paintbrush',
    'gear' => 'fa-duotone fa-gear',
    'arrow-right-from-bracket' => 'fa-duotone fa-arrow-right-from-bracket',
    'bars' => 'fa-duotone fa-bars',

    'modules' => [
        'core' => ['icon' => 'house', 'label' => 'Dashboard', 'roles' => ['*']],
        'admin' => ['icon' => 'user-shield', 'label' => 'Admin', 'roles' => ['Admin']],
        'teacherpanel' => ['icon' => 'chalkboard-teacher', 'label' => 'Teacher Panel', 'roles' => ['Professor Free', 'Professor Pro']],
        'planning' => ['icon' => 'calendar-lines-pen', 'label' => 'Planning', 'roles' => ['Professor Free', 'Professor Pro']],
        'classrecord' => ['icon' => 'book-user', 'label' => 'Class Record', 'roles' => ['Professor Free', 'Professor Pro']],
        'library' => ['icon' => 'books', 'label' => 'Library', 'roles' => ['Professor Free', 'Professor Pro', 'Admin']],
        'billing' => ['icon' => 'credit-card', 'label' => 'Billing', 'roles' => ['Professor Free', 'Professor Pro']],
        'support' => ['icon' => 'headset', 'label' => 'Support', 'roles' => ['Professor Free', 'Professor Pro']],
    ],
];
